config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit]
  get 'my_profile', to: 'users#my_profile'
  get "all_users", to: "users#index"
  put "edit_my_user", to: "users#update"
  get "edit_my_preferences/:id", to: "users#edit_preferences", as: :edit_my_preferences
  put "my_preferences", to: "users#update_preferences"

  resources :interactions, only: [:new, :create]

  resources :astrology_charts, only: [:new, :create, :edit, :update]


  resources :matches, only: [:show, :create, :destroy, :index] do
   resources :messages, only: [:create]
  end
  resources :messages, only: [:destroy]


end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController

  def new
  end

  def create
    @interaction = Interaction.new
    @interaction.sender_id = current_user.id
    @interaction.receiver_id = params[:receiver]
    @interaction.like = params[:like]
      if @interaction.save
        like_interaction = Interaction.where(sender_id: params[:receiver], receiver: current_user, like: true).any?
        if like_interaction && @interaction.like
          @match = Match.create(user_one_id: current_user.id, user_two_id: params[:receiver])
        end
        best_match
        redirect_to all_users_path(@best_match)
      else
        @user = User.find(params[:receiver])
        render { "users/show" }
      end
    end

  private

  def best_match
    users = User.where.not(id: current_user.id).joins('LEFT JOIN interactions ON interactions.sender_id = users.id OR interactions.receiver_id = users.id')
    users =  users.reject { |user| user.interactions.pluck(:sender_id).include? current_user.id }

    users = users.sort_by { |user|
         (SignMatch.find_by(sign_one_id: current_user.astrology_chart.sun_id, sign_two_id: user.astrology_chart.sun_id).percentage * 3)
       + (SignMatch.find_by(sign_one_id: current_user.astrology_chart.moon_id, sign_two_id: user.astrology_chart.moon_id).percentage * 2)
       + (SignMatch.find_by(sign_one_id: current_user.astrology_chart.ascendant_id, sign_two_id: user.astrology_chart.ascendant_id).percentage) }
    @best_match = users.first
  end
end

app/views/interactions/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: Review.new %>');
<% end %>


<script>
  decline.addEventListener('click', (event) => {
    fetch("<%= new_interaction_path(like: false, receiver: @best_match.id) %>")
  })

  approve.addEventListener('click', (event) => {
    fetch("<%= new_interaction_path(like: true, receiver: @best_match.id) %>")
  })
</script>