config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit]
  get 'my_profile', to: 'users#my_profile'
  get "all_users", to: "users#index"
  put "edit_my_user", to: "users#update"
  get "edit_my_preferences/:id", to: "users#edit_preferences", as: :edit_my_preferences
  put "my_preferences", to: "users#update_preferences"

  resources :interactions, only: [:new, :create]

  resources :astrology_charts, only: [:new, :create, :edit, :update]


  resources :matches, only: [:show, :create, :destroy, :index] do
   resources :messages, only: [:create]
  end
  resources :messages, only: [:destroy]


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sent_messages, :class_name => "Message", :foreign_key => "sender_id", dependent: :destroy
  has_many :received_messages, :class_name => "Message", :foreign_key => "receiver_id", dependent: :destroy
  validates :username, presence: true
  has_one_attached :avatar
  has_many_attached :photos
  belongs_to :state, optional: true
  has_one :astrology_chart, dependent: :destroy
  has_many :matches, dependent: :destroy
  has_many :interactions, dependent: :destroy


  def matches
    # current_user.matches ==> Match.where(user_one: current_user).or(user_two: current_user)
    Match.where(user_one: self).or(Match.where(user_two: self))
  end

  def interactions
    Interaction.where(sender: self).or(Interaction.where(receiver: self))
  end

  def sun_percentage(user)
    SignMatch.find_by(sign_one_id: astrology_chart.sun_id, sign_two_id: user.astrology_chart.sun_id).percentage
  end

  def moon_percentage(user)
    SignMatch.find_by(sign_one_id: astrology_chart.moon_id, sign_two_id: user.astrology_chart.moon_id).percentage
  end

  def ascendant_percentage(user)
    SignMatch.find_by(sign_one_id: astrology_chart.ascendant_id, sign_two_id: user.astrology_chart.ascendant_id).percentage
  end

  def match_percentage(user)
    match_result =
      (sun_percentage(user) * 3) +
      (moon_percentage(user) * 2) +
      ascendant_percentage(user)

    match_result/6
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # Pra nao quebrar na master, linha nao esta correta
    users = User.where.not(id: current_user.id).joins('LEFT JOIN interactions ON interactions.sender_id = users.id OR interactions.receiver_id = users.id')
    users =  users.reject { |user| user.interactions.pluck(:sender_id).include? current_user.id }

    users = users.sort_by { |user| current_user.match_percentage(user) }

    @best_match = users.first
    @match_percentage = current_user.match_percentage(@best_match) if @best_match.present?
  end

  def show
    @user = User.find(params[:id])
    @match_percentage = current_user.match_percentage(@user)
    @sun_percentage = current_user.sun_percentage(@user)
    @moon_percentage = current_user.moon_percentage(@user)
    @ascendant_percentage = current_user.ascendant_percentage(@user)
  end

  def my_profile
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_update_params)
      redirect_to all_users_path
    else
      render :edit
    end
  end

  def edit_preferences
    @user = User.find(params[:id])
  end

  def update_preferences
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to my_profile_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :description, :like_man, :like_woman, :avatar, :gender)
  end

  def user_update_params
    params.require(:user).permit(:username, :email, :password, :current_address)
  end

end

app/views/users/_end.html.erb
<div class="end-users-container">
    <img src="https://res.cloudinary.com/dgeodyyf7/image/upload/v1584368152/Search_illustration_hivudw.png">
    <h2>Estamos buscando mais pessoas nas estrelas!</h2>
</div>

app/views/users/edit.html.erb
<div class="edit-config-container">
    <h4>Editar Configurações</h4>
    <%= simple_form_for(@user, as: @user, url: edit_my_user_path, html: { method: :put }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :email, required: true, autofocus: true %>

        <%= f.input :username, label: "Name" %>

        <%= f.input :current_address,
                    hint: "change your current address here",
                    required: false,
                    input_html: { autocomplete: "current address" } %>

        <%= f.input :password,
                    hint: "leave it blank if you don't want to change it",
                    required: false,
                    input_html: { autocomplete: "new-password" } %>
        <%= f.input :password_confirmation,
                    required: false,
                    input_html: { autocomplete: "new-password" } %>
        <%= f.input :current_password,
                    hint: "we need your current password to confirm your changes",
                    required: true,
                    input_html: { autocomplete: "current-password" } %>


      <%= f.button :submit, "Update", class:"btn profile-btn col-sm-4 mt-1" %>
    <% end %>
</div>

app/views/users/edit_preferences.html.erb
<div class="profile-user-container">
  <div class="preferences-form-inputs">
    <h2>Edit Preferences</h2>
        <% if @user.avatar.attached? %>
            <%= cl_image_tag @user.avatar.key, height: 200, width: 200, crop: :thumb, gravity: :face %>
        <% elsif @user.gender == "male" %>
            <img src="https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-19_eufk6s.png" alt="<% @user.id %>">
        <% else %>
            <img src="https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-20_njbszk.png" alt="<% @user.id %>">
        <% end %>
        <div class="preferences-form">
          <%= simple_form_for(@user, as: @user, url: my_preferences_path, html: { method: :put }) do |f| %>
            <%= hidden_field_tag 'id', @user.id %>
            <%= f.error_notification %>

              <h5>Change profile photo:</h5>

              <%= f.input :avatar, as: :file, inline_label: 'avatar', label: false %>

              <h5>Gender:</h5>

              <%= f.input :gender, inline_label: 'avatar', label: false, collection: ["male", "female"] %>


              <h5>Description:</h5>

              <%= f.input :description, as: :text, autofocus: true, inline_label: 'Descrição', label: false %>

              <h5>Preferences:</h5>
              <div>
                <%= f.label 'Man'%>
                <%= f.check_box :like_man %>
                <%= f.label 'Woman'%>
                <%= f.check_box :like_woman %>
              </div>
            <%= f.button :submit, "Update", class:"btn preferences-btn col-sm-4 mt-1" %>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<% if @best_match.nil? %>
  <%= render "end" %>
<% else %>
  <div class="profile-container">
    <h2 id="percentage-user" class="profile-name">
      AstralMatch: <%= @match_percentage %>%
    </h2>
    <div class="profile-photo">
      <% if @best_match.avatar.attached? %>
        <%= link_to user_path(@best_match) do %>
          <%= cl_image_tag @best_match.avatar.key, height: 200, width: 200, crop: :thumb, gravity: :face %>
        <% end %>
      <% elsif @best_match.gender == "male" %>
        <%= link_to user_path(@best_match) do %>
          <img src="https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-19_eufk6s.png" alt="<% @best_match.id %>">
        <% end %>
      <% else %>
        <%= link_to user_path(@best_match) do %>
          <img src="https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-20_njbszk.png" alt="<% @best_match.id %>">
        <% end %>
      <% end %>
    </div>
    <h2 class="profile-name">
      <%= link_to user_path(@best_match) do %>
        <%= @best_match.username %>
      <% end %>
    </h2>
    <div class="signs-list">
      <div class="sign">
        <div class="sign-description">
          <h4>ASC</h4>
          <div class="icon-sign"><%= image_tag(@best_match.astrology_chart.ascendant.icon_url) %></div>
          <div class="icon-sign-text"><p><%= Sign.find_by(id: @best_match.astrology_chart.ascendant_id).sign_name %></p></div>
        </div>
      </div>
      <div class="sun-sign">
        <div class="sign-sun-description">
          <h4>SUN</h4>
          <div class="icon-sun-sign"><%= image_tag(@best_match.astrology_chart.sun.icon_url) %></div>
          <p><%= Sign.find_by(id: @best_match.astrology_chart.sun_id).sign_name %></p>
        </div>
      </div>
      <div class="sign">
        <div class="sign-description">
          <h4>MOON</h4>
          <div class="icon-sign"><%= image_tag(@best_match.astrology_chart.moon.icon_url) %></div>
          <p><%= Sign.find_by(id: @best_match.astrology_chart.moon_id).sign_name %></p>
        </div>
      </div>
    </div>
    <div class="like-buttons">
      <div class="deslike">
        <%= link_to interactions_path(like: false, receiver: @best_match.id), method: :post do %>
          <i class="fas fa-times fas-4x"></i>
        <% end %>
      </div>
      <div class="like">
        <%= link_to interactions_path(like: true, receiver: @best_match.id), method: :post do %>
          <i class="fas fa-heart fas-4x"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/my_profile.html.erb
<div class="my-user-profile-container">
  <div class="profile-photo">
          <% if @user.avatar.attached? %>
            <%= link_to my_profile_path do %>
              <%= cl_image_tag @user.avatar.key, crop: :thumb, gravity: :face %>
            <% end %>
          <% elsif @user.gender == "male" %>
            <%= link_to my_profile_path do %>
              <img src="https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-19_eufk6s.png" alt="<% @user.id %>">
            <% end %>
          <% else %>
            <%= link_to my_profile_path do %>
              <img src="https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-20_njbszk.png" alt="<% @user.id %>">
            <% end %>
          <% end %>
        </div>
        <h2 class="profile-name">My Astral Chart</h2>
        <div class="signs-list">
            <div class="sign">
              <div class="sign-description">
                <h4>ASC</h4>
                <div class="icon-sign"><%= image_tag(@user.astrology_chart.ascendant.icon_url) %></div>
                <div class="icon-sign-text"><p><%= Sign.find_by(id: @user.astrology_chart.ascendant_id).sign_name %></p></div>
              </div>
            </div>
            <div class="sun-sign">
              <div class="sign-sun-description">
                <h4>SUN</h4>
                <div class="icon-sun-sign"><%= image_tag(@user.astrology_chart.sun.icon_url) %></div>
                <p><%= Sign.find_by(id: @user.astrology_chart.sun_id).sign_name %></p>
              </div>
            </div>
            <div class="sign">
              <div class="sign-description">
                <h4>MOON</h4>
                <div class="icon-sign"><%= image_tag(@user.astrology_chart.moon.icon_url) %></div>
                <p><%= Sign.find_by(id: @user.astrology_chart.moon_id).sign_name %></p>
              </div>
            </div>
        </div>
        <h2 class="profile-name"><%= @user.username.capitalize %></h2>
        <h3><%= distance_of_time_in_words(DateTime.now, @user.astrology_chart.birthdate)%></h3>
        <p><%= @user.description %></p>
        <p>(<%= @user.gender.capitalize %>)</p>

        <div class="profile-buttons">
          <div class="row">
            <%= link_to "Preferences", edit_my_preferences_path(current_user), class:"profile-btn btn col-sm-4" %>
            <%= link_to "Configuration", edit_user_path(current_user), class:"profile-btn btn col-sm-4" %>
            <%= link_to "Recalculate Astral Chart", edit_astrology_chart_path(current_user), class:"profile-btn btn col-sm-4" %>
          </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-user-container">
      <h2 class="profile-name"><%= @match_percentage %>%</h2>
        <div class="profile-photo">
        <% if @user.avatar.attached? %>
            <%= link_to all_users_path do %>
              <h4> <%= cl_image_tag @user.avatar.key, height: 200, width: 200, crop: :thumb, gravity: :face %></h4>
            <% end %>
        <% elsif @user.gender == "male" %>
            <%= link_to user_path(@user) do %>
              <img class="d-block" id="image-carousel" src="https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-19_eufk6s.png" alt="<% @user.id %>">
            <% end %>
        <% else %>
            <%= link_to user_path(@user) do %>
              <img class="d-block" id="image-carousel" src="https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-20_njbszk.png" alt="<% @user.id %>">
            <% end %>
        <% end %>
        </div>
        <h1 class="profile-name">
          <%= link_to all_users_path do %>
            <%= @user.username %>
          <% end %>
        </h1>
        <h5 class="profile-name"><%= distance_of_time_in_words(DateTime.now, @user.astrology_chart.birthdate).capitalize%></h5>
        <p><%= @user.description %></p>
        <h5 class="profile-name"><%= @user.astrology_chart.birth_city %></h5>
        <div class="bars">
        <h6>Solar compatibility: <%= @sun_percentage %>%</h6>
          <div class="compatibility-bars">
            <div class="my-sign-icon"><%= image_tag(current_user.astrology_chart.sun.icon_url) %></div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: <%= @sun_percentage %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="user-sign-icon"><%= image_tag(@user.astrology_chart.sun.icon_url) %></div>
          </div>
          <h6>Ascendant compatibility: <%= @ascendant_percentage %>%</h6>
          <div class="compatibility-bars">
            <div class="my-sign-icon"><%= image_tag(current_user.astrology_chart.ascendant.icon_url) %></div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: <%= @ascendant_percentage %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="user-sign-icon"><%= image_tag(@user.astrology_chart.sun.icon_url) %></div>
          </div>
          <h6>Lunar compatibility: <%= @moon_percentage %>%</h6>
          <div class="compatibility-bars">
            <div class="my-sign-icon"><%= image_tag(current_user.astrology_chart.moon.icon_url) %></div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: <%= @moon_percentage %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="user-sign-icon"><%= image_tag(@user.astrology_chart.moon.icon_url) %></div>
          </div>
        </div>
        <div class="like-buttons">
          <div class="deslike">
            <%= link_to interactions_path(like: false, receiver: @user.id), method: :post do %>
              <i class="fas fa-times fas-4x"></i>
            <% end %>
          </div>
          <div class="like">
            <%= link_to interactions_path(like: true, receiver: @user.id), method: :post do %>
              <i class="fas fa-heart fas-4x"></i></i>
            <% end %>
          </div>
        </div>
</div>