config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit]
  get 'my_profile', to: 'users#my_profile'
  get "all_users", to: "users#index"
  put "edit_my_user", to: "users#update"
  get "edit_my_preferences/:id", to: "users#edit_preferences", as: :edit_my_preferences
  put "my_preferences", to: "users#update_preferences"

  resources :interactions, only: [:new, :create]

  resources :astrology_charts, only: [:new, :create, :edit, :update]


  resources :matches, only: [:show, :create, :destroy, :index] do
   resources :messages, only: [:create]
  end
  resources :messages, only: [:destroy]


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-light alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-light alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="phone-frame">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <% if params[:controller] == 'users' && params[:action] == 'index' %>
      <%= link_to all_users_path, class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/dgeodyyf7/image/upload/v1584295772/Astromatch_Elementos-18_txsezp.png" %>
      <% end %>
    <% else %>
      <h4>
        <%= link_to :back do  %>
          <%= image_tag('icons-02.png', size: "28x28") %>
        <% end %>
      </h4>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <nav class="my-2 my-md-0 mr-md-3">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <%= link_to "Browse", all_users_path, class: "text-white mr-3" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Messages", matches_path, class: "text-white mr-3" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Preferences", edit_my_preferences_path(current_user), class: "text-white mr-3" %>
              </li>
              <li class="nav-item active">
                <%= link_to "My Profile", my_profile_path, class: "text-white mr-3" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Configuration", edit_user_path(current_user), class: "text-white mr-3" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "text-white mr-3" %>
              </li>
            </ul>
          </nav>
        <% else %>
          <%= link_to "Sign in", all_users_path, class: "btn btn-secondary mr-3" %>
          <%= link_to "Sign up", all_users_path, class: "btn btn-outline-primary" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>