config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit]
  get 'my_profile', to: 'users#my_profile'
  get "all_users", to: "users#index"
  put "edit_my_user", to: "users#update"
  get "edit_my_preferences/:id", to: "users#edit_preferences", as: :edit_my_preferences
  put "my_preferences", to: "users#update_preferences"

  resources :interactions, only: [:new, :create]

  resources :astrology_charts, only: [:new, :create, :edit, :update]


  resources :matches, only: [:show, :create, :destroy, :index] do
   resources :messages, only: [:create]
  end
  resources :messages, only: [:destroy]


end

app/models/match.rb
class Match < ApplicationRecord
  has_many :messages
  belongs_to :user_one, class_name: "User"
  belongs_to :user_two, class_name: "User"
  def other_user(user)
    return user_two if user == user_one
    user_one
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController


  def index
    @matches = current_user.matches
  end

  def show
    @match = Match.find(params[:id])
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/views/matches/index.html.erb
<% if @matches.empty? %>
  <div class="card-product">

      <div class="card-product-infos">
      <h2>You don't have any matches yet.</h2>
  </div>
<% else %>
<div class="card-title">
  <h2>Chats</h2>
</div>
  <% @matches.each do |match| %>
      <%= link_to match_path(match.id) do %>
        <div class="card-product">
          <%= link_to match_path(match.id) do %>
            <% if match.other_user(current_user).avatar.attached? %>
              <div class="icon-sign-chat"><%= image_tag(match.other_user(current_user).astrology_chart.ascendant.icon_url) %></div>
              <%= cl_image_tag match.other_user(current_user).avatar.key, class: "avatar", crop: :thumb, gravity: :face %>
            <% elsif match.gender == "male" %>
              <div class="icon-sign-chat"><%= image_tag(match.other_user(current_user).astrology_chart.ascendant.icon_url) %></div>
              <%= cl_image_tag "https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-19_eufk6s.png", crop: :fill, class: "avatar" %>
            <% else %>
              <div class="icon-sign-chat"><%= image_tag(match.other_user(current_user).astrology_chart.ascendant.icon_url) %></div>
              <%= cl_image_tag "https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-20_njbszk.png", crop: :fill, class: "avatar" %>
            <% end %>
            <div class="card-product-infos">
              <% if match.user_one == current_user %>
                  <h2> <%= match.user_two.username.downcase.capitalize %></h2>
              <% else %>
                  <h2> <%= match.user_one.username.downcase.capitalize %></h2>
              <% end %>
              <% if match.messages.last.nil? %>
                <p></p>
              <% else %>
                <p><%= match.messages.last.content %></p>
              <% end %>
          <% end %>
          </div>
        </div>
      <% end %>
  <% end %>
<% end %>

app/views/matches/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 altura">
      <div class="chat-header">
        <div class="row justify-content-around">
          <div class="chat-username-name">
            <h4><%= link_to @match.other_user(current_user).username.downcase.capitalize, user_path(@match.other_user(current_user).id), class: "name" %></h4>
          </div>
          <div class="profile-photo-chat">
            <% if @match.other_user(current_user).avatar.attached? %>
              <%= cl_image_tag @match.other_user(current_user).avatar.key, class: "avatar", height: 42, width: 42, crop: :thumb, gravity: :face %>
            <% elsif @match.gender == "male" %>
              <%= cl_image_tag "https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-19_eufk6s.png", crop: :fill, class: "avatar" %>
            <% else %>
              <%= cl_image_tag "https://res.cloudinary.com/dgeodyyf7/image/upload/v1584325494/Astromatch_Elementos-20_njbszk.png", crop: :fill, class: "avatar" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="messages">
        <% @match.messages.each do |message| %>
          <%= render "messages/message", message: message, user_is_messages_author: message.from?(current_user) %>
        <% end %>
      </div>
      <div class="chat_footer">
        <div id="create-message form-inline">
          <%= simple_form_for [@match, Message.new],  wrapper: :inline_form,
            html: { class: "form-inline col-12" }, remote: true do |f| %>
            <div class="marcele">
              <%= f.input :content, as: :string, label: false %>
            </div>
            <%= button_tag type: :submit, class: 'profile-btn btn btn-circle' do %>
               <i class="fas fa-chevron-right"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    scrollLastMessageIntoView();
    App['chat_room_<%= @match.id %>'] = App.cable.subscriptions.create(
      { channel: 'ChatRoomsChannel', chat_room_id: <%= @match.id %> },
      {
        received: (data) => {
          if (data.current_user_id !== <%= current_user.id %>) {
            const messagesContainer = document.querySelector('.messages');
            messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
            document.getElementById('message_content').value = "";
            scrollLastMessageIntoView();
          }
        }
      }
    )
  </script>
<% end %>